version: '3.1'

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - db:/var/lib/mysql

  minio:
    image: minio/minio:RELEASE.2024-02-26T09-33-48Z.fips
    command: server /data --console-address ":9001"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootpassword
    ports:
      - '9000:9000'
      - '9001:9001'

  redis:
    image: redis:7.2.4-bookworm
    restart: always
    volumes:
      - redis:/data
    environment:
      REDIS_PASSWORD: 'password'
      REDIS_PORT: '6379'
    ports:
      - '6379:6379'


volumes:
  db:
    driver: local
  minio:

  redis:
    driver: local
