version: '3.1'

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    environment:
      MYSQL_DATABASE: '${MYSQL_DB}'
      MYSQL_USER: '${MYSQL_USERNAME}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db:/var/lib/mysql

  minio:
    image: minio/minio:RELEASE.2024-02-26T09-33-48Z.fips
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: '${MINIO_ACCESS_KEY}'
      MINIO_ROOT_PASSWORD: '${MINIO_SECRET_KEY}'
    ports:
      - '${MINIO_PORT}:${MINIO_PORT}'
      - '${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}'

  redis:
    image: redis:7.2.4-bookworm
    restart: always
    volumes:
      - redis:/data
    environment:
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
      REDIS_PORT: '${REDIS_PORT}'
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'


volumes:
  db:
    driver: local
  minio:

  redis:
    driver: local
